### ISSUE TITLE
Constructor to wrap billy.Filesystem

### ISSUE THREAD

**Issue by dnesting** [forensicanalysis/gitfs#18]
Requesting a way to instantiate a `GitFS` instance using a `billy.Filesystem` directly.  The main use case is for situations where I need to instantiate a go-git `Repository` separately, such as to do some modifications to the repository, but then still want to make the repo's contents available via `io.FS`.  Right now the constructors abstract away go-git entirely, requiring that I re-open the repo.

At the risk of making go-git part of your API and not just implementation, this may be as simple as making the `FS` field public, which could allow me to do this myself:

```go
	worktree, err := repository.Worktree()
	if err != nil {
		return nil, err
	}
	return &GitFS{FS: worktree.Filesystem}, err
```

Otherwise a `FromWorktree(billy.Filesystem)` function would probably meet my needs here.

**Comment by cugu** [comment]
`FS` is exported now.
